In [1]:
pwd

'C:\\Users\\91918\\rna seq'

In [2]:
import os
os.chdir("C:/Users/91918")

In [3]:
pwd

'C:\\Users\\91918'

In [104]:
import pandas as pd 
df=pd.read_excel("liver proteome1.xlsx")

In [110]:
df

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [111]:
# Filter for the "O_DR / O_AL" comparison with P-value < 0.05
df_filtered = df[(df["Comparison (group1/group2)"] == "O_DR / O_AL") & (df["Qvalue"] < 0.05)]

# Display the first few rows
display(df_filtered.head())

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
9,O_DR / O_AL,Q8C196,Q8C196,0.452917,0.452917,9.817179e-183,4.058422e-179,4559,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,36.880536,1.368805,O_DR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
18,O_DR / O_AL,P19096,P19096,-0.383790,0.383790,5.379404e-131,1.170445e-127,3020,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.357825,0.766422,O_DR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
25,O_DR / O_AL,Q91Y97,Q91Y97,0.644823,0.644823,2.083733e-113,3.313135e-110,1273,Q91Y97,Aldob,Fructose-bisphosphate aldolase B,ALDOB_MOUSE,38,56.354710,1.563547,O_DR,O_AL,"microtubule organizing center,centriolar satel...","fructose-bisphosphate aldolase activity,cytosk...","fructose metabolic process,glycolytic process,..."
29,O_DR / O_AL,Q99K67,Q99K67,0.948140,0.948140,4.600325e-105,6.339248e-102,1241,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,92.938305,1.929383,O_DR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
47,O_DR / O_AL,Q91V92,Q91V92,-0.712077,0.712077,1.034209e-91,8.907128e-89,1284,Q91V92,Sep11,ATP-citrate synthase,ACLY_MOUSE,66,-38.955936,0.610441,O_DR,O_AL,"nucleoplasm,mitochondrion,cytosol,plasma membr...","ATP citrate synthase activity,protein binding,...","acetyl-CoA biosynthetic process,citrate metabo..."

In [112]:
# Extract only the gene names that are differentially expressed
de_genes = df_filtered["Genes"].tolist()

# Display first 10 genes
print(de_genes[:10])

['Cps1', 'Fasn', 'Aldob', 'Aass', 'Sep11', 'Pc', 'Myh9', 'Sardh', 'Sept7', 'Sept9']

In [113]:
print(f"Number of differentially expressed genes (Q < 0.05) in O_DR / O_AL: {df_filtered.shape[0]}")

Number of differentially expressed genes (Q < 0.05) in O_DR / O_AL: 1343

In [114]:


# Save filtered data to an Excel file
output_file = "O_DR_O_AL_DEGs.xlsx"
df_filtered[["Genes","AVG Log2 Ratio","Qvalue"]].to_excel(output_file, index=False, engine='openpyxl')

print(f"Differentially expressed genes saved to {output_file}")

Differentially expressed genes saved to O_DR_O_AL_DEGs.xlsx