In [5]:
pwd

'C:\\Users\\91918\\rna seq'

In [6]:
import os
os.chdir("C:\\Users\\91918")

In [7]:
import pandas as pd
lp=pd.read_excel("liver proteome.xlsx")

In [ ]:
lp

In [9]:
lp.shape

(85298, 20)

In [10]:
lp.columns

Index(['Comparison (group1/group2)', 'Group', 'ProteinGroups',
       'AVG Log2 Ratio', 'Absolute AVG Log2 Ratio', 'Pvalue', 'Qvalue',
       '# of Ratios', 'UniProtIds', 'Genes', 'ProteinDescriptions',
       'ProteinNames', '# Unique Total Peptides', '% Change', 'Ratio',
       'Condition Numerator', 'Condition Denominator', 'GO Cellular Component',
       'GO Molecular Function', 'GO Biological Process'],
      dtype='object')

In [11]:
lp.head(3)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."

In [12]:
lp.tail(4)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,0.999912,0.484628,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,0.999976,0.484645,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,0.999981,0.484645,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,0.999962,0.484645,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [ ]:
lp.isna

In [14]:
print(lp["Genes"])

0           Cps1
1           Cps1
2           Cps1
3           Cps1
4           Cps1
          ...
85293       Tmx2
85294       Pin1
85295       Faf1
85296       Nono
85297    Eif2s3x
Name: Genes, Length: 85298, dtype: object

In [34]:
unique_genes=lp["Genes"].unique()
print(unique_genes)

['Cps1' 'Myh9' 'Fasn' ... 'Ccdc93' 'Mib1' 'Taok3']

In [16]:
filtered_lp = lp[lp["Comparison (group1/group2)"] == "O_AL / Y_NRDR"] 
print(filtered_lp)

      Comparison (group1/group2)   Group ProteinGroups  AVG Log2 Ratio  \
0                  O_AL / Y_NRDR  Q8C196        Q8C196       -0.809178
10                 O_AL / Y_NRDR  Q8VDD5        Q8VDD5        0.749668
11                 O_AL / Y_NRDR  P19096        P19096        0.493128
13                 O_AL / Y_NRDR  Q99K67        Q99K67       -1.294483
23                 O_AL / Y_NRDR  P24549        P24549       -0.968203
...                          ...     ...           ...             ...
84888              O_AL / Y_NRDR  Q99KY4        Q99KY4        0.282322
84977              O_AL / Y_NRDR  Q9ER35        Q9ER35        0.161770
85011              O_AL / Y_NRDR  Q9Z0U1        Q9Z0U1        0.436748
85148              O_AL / Y_NRDR  Q922B1        Q922B1        0.084755
85245              O_AL / Y_NRDR  Q6P1F6        Q6P1F6        0.006318

       Absolute AVG Log2 Ratio         Pvalue         Qvalue  # of Ratios  \
0                     0.809178   0.000000e+00   0.000000e+00         3847
10                    0.749668  1.894163e-165  7.118607e-162         2170
11                    0.493128  1.640457e-163  5.651376e-160         2578
13                    1.294483  9.519081e-149  2.810849e-145         1041
23                    0.968203  2.964165e-117  5.105774e-114          667
...                        ...            ...            ...          ...
84888                 0.282322   9.900507e-01   4.821380e-01           62
84977                 0.161770   9.922688e-01   4.827219e-01           44
85011                 0.436748   9.927627e-01   4.827749e-01          197
85148                 0.084755   9.960496e-01   4.835839e-01          109
85245                 0.006318   9.986583e-01   4.842878e-01           31

      UniProtIds    Genes                                ProteinDescriptions  \
0         Q8C196     Cps1  Carbamoyl-phosphate synthase [ammonia], mitoch...
10        Q8VDD5     Myh9                                           Myosin-9
11        P19096     Fasn                                Fatty acid synthase
13        Q99K67     Aass  Alpha-aminoadipic semialdehyde synthase, mitoc...
23        P24549  Aldh1a1                            Retinal dehydrogenase 1
...          ...      ...                                                ...
84888     Q99KY4      Gak                         Cyclin-G-associated kinase
84977     Q9ER35     Fn3k                              Fructosamine-3-kinase
85011     Q9Z0U1     Tjp2                        Tight junction protein ZO-2
85148     Q922B1  Macrod1            O-acetyl-ADP-ribose deacetylase MACROD1
85245     Q6P1F6  Ppp2r2a  Serine/threonine-protein phosphatase 2A 55 kDa...

      ProteinNames  # Unique Total Peptides   % Change     Ratio  \
0       CPSM_MOUSE                      151 -42.929303  0.570707
10      MYH9_MOUSE                      148  68.140551  1.681406
11       FAS_MOUSE                      123  40.749356  1.407494
13      AASS_MOUSE                       54 -59.231774  0.407682
23     AL1A1_MOUSE                       30 -48.885769  0.511142
...            ...                      ...        ...       ...
84888    GAK_MOUSE                        7  21.615046  1.216150
84977   FN3K_MOUSE                        4  11.865843  1.118658
85011    ZO2_MOUSE                       17  35.354938  1.353549
85148  MACD1_MOUSE                        8   6.050749  1.060507
85245   2ABA_MOUSE                        5   0.438912  1.004389

      Condition Numerator Condition Denominator  \
0                    O_AL                Y_NRDR
10                   O_AL                Y_NRDR
11                   O_AL                Y_NRDR
13                   O_AL                Y_NRDR
23                   O_AL                Y_NRDR
...                   ...                   ...
84888                O_AL                Y_NRDR
84977                O_AL                Y_NRDR
85011                O_AL                Y_NRDR
85148                O_AL                Y_NRDR
85245                O_AL                Y_NRDR

                                   GO Cellular Component  \
0      nucleolus,mitochondrion,mitochondrial inner me...
10     stress fiber,ruffle,uropod,nucleus,cytoplasm,a...
11     mitochondrion,Golgi apparatus,cytosol,plasma m...
13     mitochondrion,intracellular membrane-bounded o...
23                         cytosol,extracellular exosome
...                                                  ...
84888  Golgi apparatus,cytosol,focal adhesion,membran...
84977                                            cytosol
85011  nucleus,cytosol,plasma membrane,cell-cell junc...
85148                  nucleus,nucleoplasm,mitochondrion
85245        protein phosphatase type 2A complex,cytosol

                                   GO Molecular Function  \
0      carbamoyl-phosphate synthase (ammonia) activit...
10     microfilament motor activity,RNA binding,actin...
11     RNA binding,fatty acid synthase activity,[acyl...
13     saccharopine dehydrogenase (NADP+, L-lysine-fo...
23     retinal dehydrogenase activity,3-chloroallyl a...
...                                                  ...
84888  protein serine/threonine kinase activity,prote...
84977                     fructosamine-3-kinase activity
85011  protein binding,protein C-terminus binding,pro...
85148  hydrolase activity, acting on glycosyl bonds,d...
85245  protein serine/threonine phosphatase activity,...

                                   GO Biological Process
0      urea cycle,'de novo' pyrimidine nucleobase bio...
10     meiotic spindle organization,cell morphogenesi...
11     osteoblast differentiation,acetyl-CoA metaboli...
13     generation of precursor metabolites and energy...
23     optic cup morphogenesis involved in camera-typ...
...                                                  ...
84888  protein phosphorylation,receptor-mediated endo...
84977  phosphorylation,fructosamine metabolic process...
85011  intestinal absorption,TNFSF11-mediated signali...
85148  cellular response to DNA damage stimulus,purin...
85245  mitotic cell cycle,protein dephosphorylation,d...

[3043 rows x 20 columns]

In [17]:
num_unique_genes=lp["Genes"].nunique() 
print(f"number of unique genes: {num_unique_genes}")

number of unique genes: 3004

In [18]:
genes_in_comparison = filtered_lp["Genes"].unique() 
print(genes_in_comparison)

['Cps1' 'Myh9' 'Fasn' ... 'Tjp2' 'Macrod1' 'Ppp2r2a']

In [19]:
print(f"Number of unique genes: {len(genes_in_comparison)}")

Number of unique genes: 2995

In [20]:
print(filtered_lp.isna().sum())

Comparison (group1/group2)     0
Group                          0
ProteinGroups                  0
AVG Log2 Ratio                 0
Absolute AVG Log2 Ratio        0
Pvalue                         0
Qvalue                         0
# of Ratios                    0
UniProtIds                    21
Genes                         49
ProteinDescriptions            0
ProteinNames                   0
# Unique Total Peptides        0
% Change                       0
Ratio                          0
Condition Numerator            0
Condition Denominator          0
GO Cellular Component         57
GO Molecular Function         69
GO Biological Process         82
dtype: int64

In [21]:
pwd

'C:\\Users\\91918'

In [22]:
import os
os.chdir("C:\\Users\\91918")

In [23]:
import pandas as pd
lp1=pd.read_excel("liver proteome.xlsx")

In [24]:
lp1

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [25]:
filtered_lp1 = lp1[lp1["Comparison (group1/group2)"] == "O_NR / Y_NRDR"] 
print(filtered_lp1)

      Comparison (group1/group2)   Group ProteinGroups  AVG Log2 Ratio  \
1                  O_NR / Y_NRDR  Q8C196        Q8C196       -0.913840
15                 O_NR / Y_NRDR  Q8VDD5        Q8VDD5        0.724024
27                 O_NR / Y_NRDR  P19096        P19096        0.500641
33                 O_NR / Y_NRDR  Q99K67        Q99K67       -1.229249
39                 O_NR / Y_NRDR  P41216        P41216       -0.734297
...                          ...     ...           ...             ...
84774              O_NR / Y_NRDR  P97450        P97450       -0.241298
84805              O_NR / Y_NRDR  Q99K95        Q99K95       -0.005052
84807              O_NR / Y_NRDR  P26040        P26040       -0.093439
84963              O_NR / Y_NRDR  P70699        P70699       -0.304868
84991              O_NR / Y_NRDR  Q91V16        Q91V16        0.057653

       Absolute AVG Log2 Ratio         Pvalue         Qvalue  # of Ratios  \
1                     0.913840   0.000000e+00   0.000000e+00         3846
15                    0.724024  2.315492e-138  5.982653e-135         2159
27                    0.500641  1.225886e-105  1.809934e-102         2566
33                    1.229249  4.223843e-101   5.135696e-98         1038
39                    0.734297   5.146300e-95   5.294740e-92          782
...                        ...            ...            ...          ...
84774                 0.241298   9.874075e-01   4.815283e-01           77
84805                 0.005052   9.881327e-01   4.816853e-01           22
84807                 0.093439   9.881839e-01   4.816942e-01           58
84963                 0.304868   9.920717e-01   4.826830e-01          123
84991                 0.057653   9.925194e-01   4.827600e-01           33

      UniProtIds   Genes                                ProteinDescriptions  \
1         Q8C196    Cps1  Carbamoyl-phosphate synthase [ammonia], mitoch...
15        Q8VDD5    Myh9                                           Myosin-9
27        P19096    Fasn                                Fatty acid synthase
33        Q99K67    Aass  Alpha-aminoadipic semialdehyde synthase, mitoc...
39        P41216   Acsl1                Long-chain-fatty-acid--CoA ligase 1
...          ...     ...                                                ...
84774     P97450   Atp5j      ATP synthase-coupling factor 6, mitochondrial
84805     Q99K95  Rtfdc1                               Protein RTF2 homolog
84807     P26040     Ezr                                              Ezrin
84963     P70699     Gaa                        Lysosomal alpha-glucosidase
84991     Q91V16   Lyrm5                     LYR motif-containing protein 5

      ProteinNames  # Unique Total Peptides   % Change     Ratio  \
1       CPSM_MOUSE                      151 -46.922960  0.530770
15      MYH9_MOUSE                      148  65.178311  1.651783
27       FAS_MOUSE                      123  41.484225  1.414842
33      AASS_MOUSE                       54 -57.346067  0.426539
39     ACSL1_MOUSE                       45 -39.888919  0.601111
...            ...                      ...        ...       ...
84774  ATP5J_MOUSE                        6 -15.401611  0.845984
84805   RTF2_MOUSE                        2  -0.349562  0.996504
84807   EZRI_MOUSE                        6  -6.271440  0.937286
84963   LYAG_MOUSE                       10 -19.048385  0.809516
84991  LYRM5_MOUSE                        3   4.077091  1.040771

      Condition Numerator Condition Denominator  \
1                    O_NR                Y_NRDR
15                   O_NR                Y_NRDR
27                   O_NR                Y_NRDR
33                   O_NR                Y_NRDR
39                   O_NR                Y_NRDR
...                   ...                   ...
84774                O_NR                Y_NRDR
84805                O_NR                Y_NRDR
84807                O_NR                Y_NRDR
84963                O_NR                Y_NRDR
84991                O_NR                Y_NRDR

                                   GO Cellular Component  \
1      nucleolus,mitochondrion,mitochondrial inner me...
15     stress fiber,ruffle,uropod,nucleus,cytoplasm,a...
27     mitochondrion,Golgi apparatus,cytosol,plasma m...
33     mitochondrion,intracellular membrane-bounded o...
39     mitochondrion,mitochondrial outer membrane,per...
...                                                  ...
84774  mitochondrial proton-transporting ATP synthase...
84805                                            nucleus
84807  fibrillar center,ruffle,immunological synapse,...
84963  lysosome,lysosomal membrane,membrane,extracell...
84991                                      mitochondrion

                                   GO Molecular Function  \
1      carbamoyl-phosphate synthase (ammonia) activit...
15     microfilament motor activity,RNA binding,actin...
27     RNA binding,fatty acid synthase activity,[acyl...
33     saccharopine dehydrogenase (NADP+, L-lysine-fo...
39     long-chain fatty acid-CoA ligase activity,ATP ...
...                                                  ...
84774  hydrogen ion transmembrane transporter activit...
84805                                 molecular_function
84807  RNA binding,actin binding,protein binding,micr...
84963  alpha-1,4-glucosidase activity,oligo-1,6-gluco...
84991                                 molecular_function

                                   GO Biological Process
1      urea cycle,'de novo' pyrimidine nucleobase bio...
15     meiotic spindle organization,cell morphogenesi...
27     osteoblast differentiation,acetyl-CoA metaboli...
33     generation of precursor metabolites and energy...
39     long-chain fatty acid metabolic process,trigly...
...                                                  ...
84774  ATP synthesis coupled proton transport,substan...
84805  site-specific DNA replication termination at R...
84807  negative regulation of transcription from RNA ...
84963  maltose metabolic process,regulation of the fo...
84991               respiratory electron transport chain

[3044 rows x 20 columns]

In [26]:
num_unique_genes = lp1["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

number of unique genes: 3004

In [27]:
genes_in_comparison = filtered_lp1["Genes"].unique() 
print(genes_in_comparison)

['Cps1' 'Myh9' 'Fasn' ... 'Ezr' 'Gaa' 'Lyrm5']

In [28]:
print(f"Number of unique genes: {len(genes_in_comparison)}")

Number of unique genes: 2996

In [29]:
print(filtered_lp1.isna().sum())

Comparison (group1/group2)     0
Group                          0
ProteinGroups                  0
AVG Log2 Ratio                 0
Absolute AVG Log2 Ratio        0
Pvalue                         0
Qvalue                         0
# of Ratios                    0
UniProtIds                    21
Genes                         49
ProteinDescriptions            0
ProteinNames                   0
# Unique Total Peptides        0
% Change                       0
Ratio                          0
Condition Numerator            0
Condition Denominator          0
GO Cellular Component         57
GO Molecular Function         69
GO Biological Process         82
dtype: int64

In [35]:
pwd

'C:\\Users\\91918'

In [31]:
import pandas as pd
lp2 = pd.read_excel("liver proteome.xlsx")

In [36]:
lp2

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [ ]:
filtered_lp2= lp2[lp2["Comparison (group1/group2)"] == "O_NR / Y_DR"] 
print(filtered_lp2)

In [ ]:
genes_in_comparison = filtered_lp2["Genes"]
print(genes_in_comparison)

In [ ]:
print(f"Number of unique genes: {len(genes_in_comparison)}")

In [ ]:
print(filtered_lp2.isna().sum())

In [ ]:
pwd

In [ ]:
lp3 = pd.read_excel("liver proteome.xlsx")

In [ ]:
lp3

In [ ]:
filtered_lp3 = lp3[lp3["Comparison (group1/group2)"] == "O_AL / Y_DR"]
print(filtered_lp3)

In [ ]:
num_unique_genes=lp3["Genes"].nunique() 
print(f"number of unique genes: {num_unique_genes}")

In [ ]:
genes_in_comparison = filtered_lp3["Genes"]
print(genes_in_comparison)

In [ ]:
print(filtered_lp3.isna().sum())

In [ ]:
pwd

In [ ]:
lp4=pd.read_excel("liver proteome.xlsx")

In [ ]:
lp4

In [ ]:
filtered_lp4 =lp4[lp4["Comparison (group1/group2)"] == "O_NRDR / O_NR"]
print(filtered_lp4)

In [ ]:
num_unique_genes = lp4["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

In [ ]:
genes_in_comparison = filtered_lp4["Genes"]
print(genes_in_comparison)

In [ ]:
print(filtered_lp4.isna().sum())

In [ ]:
pwd

In [ ]:
lp5=pd.read_excel("liver proteome.xlsx")

In [ ]:
lp5

In [ ]:
filtered_lp5=lp5[lp5["Comparison (group1/group2)"]== "O_NRDR / O_AL"]
print(filtered_lp5)

In [ ]:
num_unique_genes=lp5["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

In [ ]:
genes_in_comparison = filtered_lp5["Genes"]
print(genes_in_comparison)

In [ ]:
print(filtered_lp5.isna().sum())

In [ ]:
pwd

In [ ]:
lp6=pd.read_excel("liver proteome.xlsx")

In [ ]:
lp6

In [ ]:
filtered_lp6=lp6[lp6["Comparison (group1/group2)"]== "O_NRDR / O_AL"]
print(filtered_lp6)

In [ ]:
num_unique_genes=lp6["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

In [ ]:
genes_in_comparison = filtered_lp6["Genes"]
print(genes_in_comparison)

In [ ]:
print(filtered_lp6.isna().sum())

In [ ]:
pwd

In [ ]:
import os 
os.chdir("C://Users//91918")

In [ ]:
pwd

In [ ]:
import pandas as pd
lp7=pd.read_excel("liver proteome.xlsx")

In [ ]:
lp7

In [ ]:
filtered_lp7=lp7[lp7["Comparison (group1/group2)"]== "O_DR / O_AL"]
print(filtered_lp7)

In [ ]:
num_unique_genes=lp7["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

In [ ]:
genes_in_comparison = filtered_lp7["Genes"]
print(genes_in_comparison)

In [ ]:
print(filtered_lp7.isna().sum())

In [ ]:
pwd

In [ ]:
lp7=pd.read_excel("liver proteome.xlsx")