In [1]:
pwd

'C:\\Users\\91918\\rna seq'

In [2]:
import os
os.chdir("C:/Users/91918")

In [4]:
import pandas as pd
df=pd.read_excel("liver proteome.xlsx")

In [5]:
df

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [6]:
filtered_df = df[df["Comparison (group1/group2)"] == "O_DR / O_AL"]
print(filtered_df)

      Comparison (group1/group2)   Group ProteinGroups  AVG Log2 Ratio  \
9                    O_DR / O_AL  Q8C196        Q8C196        0.452917
18                   O_DR / O_AL  P19096        P19096       -0.383790
25                   O_DR / O_AL  Q91Y97        Q91Y97        0.644823
29                   O_DR / O_AL  Q99K67        Q99K67        0.948140
47                   O_DR / O_AL  Q91V92        Q91V92       -0.712077
...                          ...     ...           ...             ...
85201                O_DR / O_AL  Q8BHD7        Q8BHD7       -0.126343
85214                O_DR / O_AL  O88543        O88543       -0.238335
85220                O_DR / O_AL  Q9CQB2        Q9CQB2        0.243283
85274                O_DR / O_AL  Q9WTI7        Q9WTI7        0.088705
85297                O_DR / O_AL  Q9Z0N1        Q9Z0N1        0.032731

       Absolute AVG Log2 Ratio         Pvalue         Qvalue  # of Ratios  \
9                     0.452917  9.817179e-183  4.058422e-179         4559
18                    0.383790  5.379404e-131  1.170445e-127         3020
25                    0.644823  2.083733e-113  3.313135e-110         1273
29                    0.948140  4.600325e-105  6.339248e-102         1241
47                    0.712077   1.034209e-91   8.907128e-89         1284
...                        ...            ...            ...          ...
85201                 0.126343   9.973805e-01   4.839235e-01          103
85214                 0.238335   9.978434e-01   4.840683e-01           95
85220                 0.243283   9.979759e-01   4.841098e-01           38
85274                 0.088705   9.994361e-01   4.845157e-01          305
85297                 0.032731   9.999621e-01   4.846447e-01           86

      UniProtIds    Genes                                ProteinDescriptions  \
9         Q8C196     Cps1  Carbamoyl-phosphate synthase [ammonia], mitoch...
18        P19096     Fasn                                Fatty acid synthase
25        Q91Y97    Aldob                   Fructose-bisphosphate aldolase B
29        Q99K67     Aass  Alpha-aminoadipic semialdehyde synthase, mitoc...
47        Q91V92     Acly                               ATP-citrate synthase
...          ...      ...                                                ...
85201     Q8BHD7    Ptbp3             Polypyrimidine tract-binding protein 3
85214     O88543    Cops3                 COP9 signalosome complex subunit 3
85220     Q9CQB2  Fam195a                                    Protein FAM195A
85274     Q9WTI7    Myo1c                           Unconventional myosin-Ic
85297     Q9Z0N1  Eif2s3x  Eukaryotic translation initiation factor 2 sub...

      ProteinNames  # Unique Total Peptides   % Change     Ratio  \
9       CPSM_MOUSE                      151  36.880536  1.368805
18       FAS_MOUSE                      123 -23.357825  0.766422
25     ALDOB_MOUSE                       38  56.354710  1.563547
29      AASS_MOUSE                       54  92.938305  1.929383
47      ACLY_MOUSE                       66 -38.955936  0.610441
...            ...                      ...        ...       ...
85201  PTBP3_MOUSE                        8  -8.384904  0.916151
85214   CSN3_MOUSE                        7 -15.227682  0.847723
85220  F195A_MOUSE                        3  18.368346  1.183683
85274  MYO1C_MOUSE                       22   6.341527  1.063415
85297   IF2G_MOUSE                       15   2.294686  1.022947

      Condition Numerator Condition Denominator  \
9                    O_DR                  O_AL
18                   O_DR                  O_AL
25                   O_DR                  O_AL
29                   O_DR                  O_AL
47                   O_DR                  O_AL
...                   ...                   ...
85201                O_DR                  O_AL
85214                O_DR                  O_AL
85220                O_DR                  O_AL
85274                O_DR                  O_AL
85297                O_DR                  O_AL

                                   GO Cellular Component  \
9      nucleolus,mitochondrion,mitochondrial inner me...
18     mitochondrion,Golgi apparatus,cytosol,plasma m...
25     microtubule organizing center,centriolar satel...
29     mitochondrion,intracellular membrane-bounded o...
47     nucleoplasm,mitochondrion,cytosol,plasma membr...
...                                                  ...
85201                                            nucleus
85214       nucleus,nucleoplasm,cytosol,COP9 signalosome
85220       nucleus,cytoplasm,cytoplasmic stress granule
85274  nuclear pore,nucleolus,cytoplasm,cytosol,plasm...
85297  cytoplasm,eukaryotic translation initiation fa...

                                   GO Molecular Function  \
9      carbamoyl-phosphate synthase (ammonia) activit...
18     RNA binding,fatty acid synthase activity,[acyl...
25     fructose-bisphosphate aldolase activity,cytosk...
29     saccharopine dehydrogenase (NADP+, L-lysine-fo...
47     ATP citrate synthase activity,protein binding,...
...                                                  ...
85201                                        RNA binding
85214                                    protein binding
85220                                    protein binding
85274  microfilament motor activity,actin binding,rec...
85297  translation initiation factor activity,GTPase ...

                                   GO Biological Process
9      urea cycle,'de novo' pyrimidine nucleobase bio...
18     osteoblast differentiation,acetyl-CoA metaboli...
25     fructose metabolic process,glycolytic process,...
29     generation of precursor metabolites and energy...
47     acetyl-CoA biosynthetic process,citrate metabo...
...                                                  ...
85201  mRNA processing,RNA splicing,negative regulati...
85214  protein deneddylation,in utero embryonic devel...
85220                                 biological_process
85274  protein targeting,protein targeting to membran...
85297                           translational initiation

[3050 rows x 20 columns]

In [22]:
num_unique_genes = len(unique_genes)
print(f"Total number of unique genes: {num_unique_genes}")

Total number of unique genes: 2999

In [10]:
import numpy as np

has_nan = np.any(pd.isna(unique_genes)) 

if has_nan:
    print("There are NaN values in the unique genes.")
else:
    print("No NaN values in the unique genes.")

There are NaN values in the unique genes.

In [11]:
num_nan = np.sum(pd.isna(unique_genes))  # Count NaN values
print(f"Number of NaN values in unique genes: {num_nan}")

Number of NaN values in unique genes: 1

In [15]:
num_na_genes = na_genes.shape[0]
print(f"Number of NaN values in 'Genes': {num_na_genes}")

Number of NaN values in 'Genes': 51

In [18]:
num_actual_unique_genes = len(unique_genes)
print(f"Total actual unique genes (without NaN): {num_actual_unique_genes}")

Total actual unique genes (without NaN): 2999

In [19]:
num_genes = filtered_df["Genes"].notna().sum()
print(f"Total number of genes in 'O_DR / O_AL' comparison: {num_genes}")

Total number of genes in 'O_DR / O_AL' comparison: 2999

In [21]:
genes_in_comparison = filtered_df["Genes"]
print(genes_in_comparison)

9           Cps1
18          Fasn
25         Aldob
29          Aass
47          Acly
          ...
85201      Ptbp3
85214      Cops3
85220    Fam195a
85274      Myo1c
85297    Eif2s3x
Name: Genes, Length: 3050, dtype: object

In [7]:
pwd

'C:\\Users\\91918\\rna seq'

In [4]:
import os
os.chdir("C://Users//91918")

In [5]:
import pandas as pd
df1=pd.read_excel("liver proteome.xlsx")

In [8]:
df1

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [9]:
filtered_df1= df1[df1["Comparison (group1/group2)"] == "O_NR / O_AL"]
print(filtered_df1)

      Comparison (group1/group2)   Group ProteinGroups  AVG Log2 Ratio  \
3678                 O_NR / O_AL  Q99PL5        Q99PL5       -0.123758
3833                 O_NR / O_AL  P97501        P97501       -0.373383
3919                 O_NR / O_AL  P43883        P43883        0.524577
4995                 O_NR / O_AL  P25688        P25688       -0.308591
5092                 O_NR / O_AL  Q8CC88        Q8CC88        0.152147
...                          ...     ...           ...             ...
85130                O_NR / O_AL  Q8C0D5        Q8C0D5       -0.093973
85135                O_NR / O_AL  O08573        O08573       -0.080574
85140                O_NR / O_AL  Q61112        Q61112        0.041969
85183                O_NR / O_AL  Q6P542        Q6P542        0.231689
85216                O_NR / O_AL  Q8R1Q9        Q8R1Q9        0.073797

       Absolute AVG Log2 Ratio        Pvalue        Qvalue  # of Ratios  \
3678                  0.123758  3.434753e-13  3.859546e-12         1612
3833                  0.373383  7.524971e-13  8.113779e-12          530
3919                  0.524577  1.167484e-12  1.231219e-11          286
4995                  0.308591  1.291291e-10  1.068494e-09          886
5092                  0.152147  1.842818e-10  1.495820e-09         1010
...                        ...           ...           ...          ...
85130                 0.093973  9.956963e-01  4.835146e-01           83
85135                 0.080574  9.958675e-01  4.835625e-01          203
85140                 0.041969  9.959198e-01  4.835664e-01           24
85183                 0.231689  9.969824e-01  4.838266e-01          180
85216                 0.073797  9.978415e-01  4.840683e-01           48

      UniProtIds   Genes                                ProteinDescriptions  \
3678      Q99PL5   Rrbp1                         Ribosome-binding protein 1
3833      P97501    Fmo3  Dimethylaniline monooxygenase [N-oxide-forming] 3
3919      P43883   Plin2                                        Perilipin-2
4995      P25688     Uox                                            Uricase
5092      Q8CC88    Vwa8  von Willebrand factor A domain-containing prot...
...          ...     ...                                                ...
85130     Q8C0D5  Eftud1  Elongation factor Tu GTP-binding domain-contai...
85135     O08573  Lgals9                                         Galectin-9
85140     Q61112    Sdf4                     45 kDa calcium-binding protein
85183     Q6P542   Abcf1         ATP-binding cassette sub-family F member 1
85216     Q8R1Q9    Rbks                                         Ribokinase

      ProteinNames  # Unique Total Peptides   % Change     Ratio  \
3678   RRBP1_MOUSE                       85  -8.220595  0.917794
3833    FMO3_MOUSE                       26 -22.803003  0.771970
3919   PLIN2_MOUSE                       17  43.851128  1.438511
4995    URIC_MOUSE                       30 -19.257009  0.807430
5092    VWA8_MOUSE                       72  11.122172  1.111222
...            ...                      ...        ...       ...
85130  ETUD1_MOUSE                        8  -6.306077  0.936939
85135   LEG9_MOUSE                       13  -5.431855  0.945681
85140  CAB45_MOUSE                        2   2.951821  1.029518
85183  ABCF1_MOUSE                       15  17.420850  1.174208
85216   RBSK_MOUSE                        4   5.248339  1.052483

      Condition Numerator Condition Denominator  \
3678                 O_NR                  O_AL
3833                 O_NR                  O_AL
3919                 O_NR                  O_AL
4995                 O_NR                  O_AL
5092                 O_NR                  O_AL
...                   ...                   ...
85130                O_NR                  O_AL
85135                O_NR                  O_AL
85140                O_NR                  O_AL
85183                O_NR                  O_AL
85216                O_NR                  O_AL

                                   GO Cellular Component  \
3678   ribosome,integral component of endoplasmic ret...
3833   endoplasmic reticulum membrane,integral compon...
3919   nucleus,cytoplasm,lipid particle,cytosol,plasm...
4995                            mitochondrion,peroxisome
5092                  extracellular region,mitochondrion
...                                                  ...
85130                                                NaN
85135  extracellular region,intracellular,nucleus,cyt...
85140  late endosome,Golgi apparatus,Golgi lumen,memb...
85183  nuclear envelope,nucleoplasm,cytoplasm,cytosol...
85216            nucleus,cytoplasm,extracellular exosome

                                   GO Molecular Function  \
3678                   receptor activity,protein binding
3833   monooxygenase activity,N,N-dimethylaniline mon...
3919                                     protein binding
4995                              urate oxidase activity
5092      molecular_function,ATP binding,ATPase activity
...                                                  ...
85130  translation elongation factor activity,GTPase ...
85135  receptor binding,protein binding,galactoside b...
85140                                calcium ion binding
85183  RNA binding,ATP binding,translation activator ...
85216  ribokinase activity,ATP binding,carbohydrate k...

                                   GO Biological Process
3678   translation,signal transduction,protein transport
3833                         oxidation-reduction process
3919   response to organic cyclic compound,long-chain...
4995   purine nucleobase metabolic process,urate cata...
5092                                  biological_process
...                                                  ...
85130  translational elongation,mature ribosome assem...
85135  positive regulation of cytokine production,imm...
85140  UV protection,cerebellum development,fat cell ...
85183  translational initiation,positive regulation o...
85216  D-ribose catabolic process,carbohydrate phosph...

[3052 rows x 20 columns]

In [35]:
num_unique_genes=df1["Genes"].nunique()
print(f"number of unique genes: {num_unique_genes}")

number of unique genes: 3004

In [29]:
unique_genes=3004
display(unique_genes)

3004

In [38]:
unique_genes_list = list(unique_genes)

for gene in unique_genes_list:
    print(gene)

Cps1
Myh9
Fasn
Aass
Fth1
Aldh1a1
Sardh
Aldob
Pc
Ehhadh
Acsl1
Cyp3a41a
Ephx1
Acly
Rgn
Cyp2e1
Acadvl
A1bg
Pklr
Cyp2f2
Inmt
Cyp4a14
Cyp4a10
Fn1
A2m
Pygl
Oat
Tgm1
Dmgdh
Apoa1
Aifm1
Cpt2
Mug1
Got2
Cyp17a1
Aco2
Fmo3
Papss2
Rrbp1
Mdh2
Acaa2
Hspg2
Itih4
Acadm
Fmo1
Gls2
Fabp1
Uqcrc2
Vim
Atp5a1
Etfb
Cp
Hibadh
Lasp1
Vwa8
Pdia4
Pgd
Hmgcs2
Serpinb1a
Cpt1a
Tf
Aldh7a1
Gstm2
Cyp1a2
Hsd17b2
Por
Slc25a13
Lmna
Gstm1
Ighm
Hadha
Bag3
Ogdh
Hsdl2
Ak2
Acat1
Fmo5
Alb
Pdia3
Agxt2
Actn4
Acadl
Ugdh
Aldh1l1
Acox2
Hadhb
Gldc
Fga
Rpl7
Aco1
Hpd
Me1
Plin2
Akr1c6
Sord
Tln1
Sdha
Tkt
Atp5c1
Cpox
Ephx2
Ethe1
Decr1
Acsm5
Cyp2c40
Fgb
Acox1
Arg1
Plec
Cyc1
Hspa5
Ass1
Bhmt
Ces1
Ccbl2
Cyp27a1
Upb1
Echs1
nan
Cyp3a11
Hal
Ca3
Hadh
Acacb
Acaca
Agxt
Etfa
Acsl5
Ces1d
Cth
Gpx1
Serpina3k
Keg1
Psmb8
Slc4a1
Ech1
Slc25a10
Glul
Aldoa
Ldha
Tkfc
Ca1
Ak4
P4hb
Hpx
Atp5b
Sptbn1
Aldh1a7
Idh2
Asl
Cox4i1
Ftl1
Cyb5r3
Aldh6a1
Hmgcl
Uqcrb
Acad8
Hpgd
Clec4f
Csad
Rpn1
Hsd17b13
Sult1a1
Ahcy
Aadat
Ugp2
Kmo
Hspd1
Hacl1
Suclg1
Cyp2c54
Cyp2b9
Chdh
Eci2
Aldh5a1
Etfdh
Dld
Eci1
Uqcrfs1
Dbi
Atp11c
Gm4952
Hsp90b1
Cbs
Immt
Stat3
Acy3
Fabp2
Mettl7b
Canx
Hba
Uox
Pm20d1
Aldh1b1
Sqrdl
Hbb-b1
Fads2
Sult2a1
Fgg
Cyp2j5
Uqcrc1
Cyp2c70
Eno1
Maob
Atp5f1
Mvp
Cyp8b1
Mttp
Cycs
Flna
Acsm3
Dpysl2
Mat1a
Etnppl
Slc25a22
C4b
Apoe
Acy1
Adck3
Abcd2
Prodh
Prdx4
Gys2
Cyp3a16
Tufm
Hsp90ab1
Pter
Cox6c
Aldh3a2
Gne
Egfr
Dlst
Eprs
Mpst
Tgm2
Hdlbp
Pkm
Ugt2b17
Lrp1
Tdo2
Slc9a3r1
Sdhb
Iqgap2
Park7
Asgr1
Hibch
Crat
Tars
Vars
Atp5h
Hspe1
Slc25a5
Sec14l2
Des
Calr
Aldh16a1
Aldh4a1
Aacs
Sod1
Khsrp
Iigp1
Sult1d1
Tgfbi
Pcca
Copa
Dhcr24
Itih1
Man2a1
Ganab
Glyat
Otc
Bckdha
Akr1d1
Ndufa7
Gclc
Acss3
Cox6a1
Gstp1
Cndp2
Dpys
Slc25a3
Cenpv
Hyou1
Samhd1
Ddx1
Pbld2
D10Jhu81e
Phb2
Cox5b
Pgk1
Pitrm1
Aspdh
2009-09-01 00:00:00
Echdc1
Sec14l4
Ftcd
Cyp51a1
Acads
Hspa9
Steap4
Cyp2d26
Cyp3a25
Ncl
Gns
Eef2
Dhrs1
Gpt
Qprt
Suclg2
Erap1
Ces2c
Hsd17b6
Sult3a1
Hspa8
Pdia6
Ugt1a9
Vwa5a
H1f0
Gstm3
Pdia5
Nqo1
Rdh7
Spr
Tnks1bp1
Slc25a15
Gsta3
Psme2
Cyp4v2
Gstt2
Chil3
Gpd2
Gss
Ndufs1
Txnrd2
Pccb
Hist1h4a
Ndufa10
Crot
Hmgcs1
Ndufb5
Hsd3b3
Lcp1
Ces3a
Slc22a1
Gcdh
Myo18a
Grhpr
Rbm3
Ndufb4
Lonp1
Hoga1
Ndufv1
Sfxn1
Cyp4f14
Ndufa12
Scly
Cyp2d10
Dcxr
Rpl5
Pah
Got1
Acss2
Mut
Dbt
Copb1
Hsd17b11
Dsp
Pon1
Fdps
Hsd17b10
Cobll1
C3
Dhrs4
Rpl4
Hist1h1e
Ugt2a3
Ndufs2
Cyp2c37
Cyp2a4
Bbox1
Hnrnpa2b1
Rmdn2
Fh
Acp6
Bpgm
Gckr
Cisd1
Cyp2c50
Psme1
Cox6b1
Ces1e
Pdha1
Ctsd
Rtcb
Acad10
Abhd14b
Lgals1
Pgam1
Acbd5
Col1a2
Pdlim1
Tpi1
Pdcd4
Sod2
Scp2
Tpm4
Fabp5
Psmb5
Col6a2
Sec31a
Coq7
Bdh1
Gulo
Lss
Stat1
Ca2
Hsd3b7
Kynu
Spta1
Snd1
Ddah1
Msn
Tpt1
Clybl
Cmbl
Cyb5a
Copb2
Acot12
Col4a2
Opa1
Abat
Decr2
Ndufa9
Qdpr
Bphl
Cap1
Hao1
Mogs
Aldoc
Rnpep
Mthfd1
Uqcrq
Slc27a2
Slc38a3
Ndufc2
Blvra
Cox5a
Mug2
Dhrs7b
Cryz
Ddost
Serpinc1
Anpep
Glrx
Slc25a20
Fech
Col14a1
Ttpa
Gpt2
Abcd3
Vdac3
Lmnb2
Ttr
Elovl2
Arhgdia
Ivd
Mtco2
Ldhd
Ndufb10
Hnrnpd
Dcn
Dsg2
Suox
Gnb2l1
Ces2a
Entpd5
Ndufb11
Pabpc1
Ca5a
Vdac2
Plg
Sacm1l
Ndufa11
Gapdh
Acot3
Kng1
Prelp
Vdac1
2002-09-01 00:00:00
Hgd
Sptb
Ccbl1
Mdh1
2002-03-01 00:00:00
Stt3a
Sephs2
Abcc6
Gck
Actn1
Acaa1a
Map4
Fkbp4
Prdx1
Ak3
Cttn
Apob
Aspg
Gpi
Paics
Lman2
Cyp3a13
Acot11
Aldh9a1
Ndufs6
Gsta2
Dpyd
Lap3
Coq6
Kars
Esd
Serping1
Pigr
Cbr1
Ppia
Ndufb9
Vapb
Aars
Ddt
Sds
Dync1h1
Hexb
Ndrg2
Myg1
Fads1
Cryl1
Hnrnpm
Endog
Acot1
Nme1
Pdk1
Hp
Hnrnpl
Acsf2
Gnmt
Cotl1
Cnpy2
Cars
Timm44
Atp5o
Adhfe1
Tagln2
Stbd1
Adk
Psmb10
Ces3b
F2
Glud1
Gbp2
Eif4a2
Aadac
Htatip2
Mgst1
Rbm14
Vnn1
Cyp2a5
Lmnb1
Nudt7
Grb2
Dnaja3
Eps8l2
Gstk1
Col6a1
Dcps
Phb
Hebp1
Abcb11
Acot13
Coro1b
Ndufa2
Oasl1
Agmat
Acaa1b
Iars
Gsdmdc1
Taldo1
Sdhc
Atad3
S100a9
Cct2
Cyp2a12
Wdr1
Asph
Hist2h2ac;Hist2h2aa1
Gamt
Serpinb6
Tapbp
Khk
Pdhb
Tpm3
Isca2
Snx5
Ndufs7
Sucla2
Igh-3
Lrrc59
Pfkfb1
Pcyox1
Rpn2
Cfh
Letm1
Fabp4
Eif3l
Sri
Gphn
Ndufs8
Lsr
Acadsb
Fdx1
Rab18
Rmdn3
Tpp2
Akr1a1
Hmgb1
Pbld1
Idh3a
Prkcsh
Col1a1
Ank1
Plin3
Arpc3
Rpl13
Ndufs3
Atp2a2
Sts
Impa1
Echdc2
Anxa5
Comt
Hsd17b12
Cd36
Myl12b
Mvk
Lbr
Rps19
Gpd1
Haao
Ndufa13
Fkbp8
Slco1b2
Xdh
Pdhx
Lonp2
H2-K1
Ppa1
Psma6
Paqr9
Eef1g
Slc26a1
H6pd
Lipa
Mup2
Rars
Arfgap2
Carkd
Hsd17b8
Yars
Srp54
Cyb5b
Ranbp1
Gart
Srp68
Naprt
Pfkl
Mlec
Cbr4
Krt8
Chchd3
Pipox
Serpina6
Akr1b1
Abcd1
Mrpl12
Ywhah
Anxa11
Dbnl
Eppk1
Fahd1
Sult1b1
Oxsm
Prep
Slc25a11
Oplah
As3mt
Gchfr
Anxa7
Abcc2
Rps3a
Nsdhl
Enpep
Rab1A
Psma4
Ppp1r12a
Ttc36
Ndufv2
Pacsin3
Uroc1
Eef1d
Gjb1
Trim28
Ppa2
Hnrnpab
Cbx3
Cct3
Anxa1
Rbp4
Mvd
Scpep1
Rps9
Atp5e
Ugt3a1
Atp5l
Sec22b
Usmg5
Sarnp
Psma1
Hrg
Hspb1
Pdk2
Aldh2
Gstt1
Phyh
Ruvbl1
Dnajb11
Idh1
Aimp1
Pir
Cgn
Nit2
Arcn1
Nipsnap1
Upf1
Hint2
Gpd1l
Hspa1b;Hspa1a
Itih2
Cltc
Gmppb
Hip1r
Uck1
Hagh
Eif4g1
Chchd2
Adi1
Thnsl2
Snx2
Lgals3
Parp9
Ndufb6
Rnaset2
Actr3
Lpgat1
Ndufa6
Ppp1r7
Gsta4
Hspb8
Scarb2
Gimap4
Ndufa8
Dctn2
Nadk2
Glrx5
Pfn1
Ckb
Adh4
Tst
Ngp
Aox3
Lactb
Lrpap1
Rpl18
Rpl26
Actr2
Cluh
Pgm3
Slc25a21
Clmn
Shmt1
Abcf1
Tbl2
Erp29
Txnl1
Srsf3
Bcap31
Coq9
Casp6
Ube2n
Hrsp12
Tat
Ces2e
Eif3b
Apool
Mrps36
Clta
Npm1
Spcs2
Nme3
Flnb
Coro1a
Prrc1
Uba1
Slc25a12
Lpp
Mtch2
Scfd1
2007-09-01 00:00:00
Elovl5
Rps4x
Ppif
Marcks
Samm50
Os9
Acad9
Rdh11
Calu
Snrnp70
Pura
Gk
Sec23b
Amt
Nags
Lamb2
Tmem214
Npc1
Acp5
G6pdx
Ptma
Ggct
Rab6a
Itpr2
Gpam
Crip2
Hnrnpa0
Pa2g4
Mtdh
Urad
Ppid
Alcam
Rab21
Hist1h1a
Gmppa
Glyctk
Wibg
Atp5i
Znf326
Ddb1
Fcgr2
Eif3d
Apoa4
Maoa
Pck1
Abhd6
Atp5d
Ewsr1
Clpp
Rps6
Anxa2
Gch1
Hsd17b4
Tbca
Mup3
Tmed9
Mbl1
Cdc37
Cs
Clpx
Atic
Tmbim6
Gstm6
Pdcd5
Apex1
Anp32a
Ugt1a1
Tmem30a
Adh5
Retsat
Lgals3bp
Mbl2
Psmb9
Ddx58
Hsd11b1
Glb1
Pla2g15
Pcbp1
Ptpn6
Fbp1
Cct8
Lace1
Hmga1
Faah
Rpl6
Acnat1
Gsn
Ndufs4
Pex5
Tmed2
Kctd12
Selenbp1
Sult1e1
Hmox2
Lamp2
Pdcd6ip
Fah
Basp1
Pex11a
Cyp2d9
Myo6
Atp5j2
Eif3a
Dera
Umps
Hnrnpk
Hist1h1c
Hsd17b7
Ctnna1
Dlat
Hnrnpc
Vat1
Idi1
Fggy
Mov10
Dhx9
Tlcd2
Ifitm3
Prdx5
Slco1a4
Sgpl1
Irgm1
Rpl18a
Rpl21
L2hgdh
Ghr
Prdx3
Glo1
Naga
Swap70
Copg1
Fis1
Capza1
Pnpo
Cyp2b10
Pdlim5
Iqgap1
Ufc1
Rpl8
Adssl1
Ywhaz
Tpd52
Rhog
Sod3
Copz1
Sf3a2
Ugt1a6
Macrod1
Rpl28
Selenbp2
Sirt5
Eif4a3
Grpel1
Bdh2
Pmvk
Farsb
Atp6v0d1
Carhsp1
Ugt3a2
Eif4a1
Hist1h1d
Idh3g
Rps28
Cfb
Vasp
Dnpep
Eef1b
Uqcr10
Ilf2
Auh
Kank2
Wdtc1
Cpped1
Mia3
Pip4k2b
Lima1
Rdx
Stard5
Tmem11
Ddx17
Srsf1
Dpp4
Tmem205
Lrpprc
Snx12
Arpc5
Clic1
Tecr
Pik3ap1
Sar1b
Cand1
Ndufb8
Ctsz
Ndufb3
Zyx
Bgn
Ccdc47
Blvrb
Vcl
Rpl7a
Lyn
Ykt6
Dap
Mccc2
Tjp1
Acat2
Cct5
Rai14
Slc38a4
Fam213a
Ahsa1
Rbmxl1
Ddx5
Rplp0
Agpat2
Vti1b
Rplp2
Thrsp
Fus
Nudt12
Arhgap1
Pmpca
Ctss
Serpinf2
Plbd1
Ctnnb1
Slc23a1
Dpp7
Klkb1
A1cf
Itgb1
Ccdc124
Pon3
Pdxdc1
Lypla1
Ndufa4
Uggt1
Xpnpep1
Srsf6
Slc29a1
Poldip2
Vps26b
Dars
Psmd9
Mars
Stx4
Nucb1
Rpl19
Ap3b1
Sub1
Mpc1
Ide
Snx6
Impdh2
Txndc5
Cfl2
Hykk
Mccc1
Rab5c
Stt3b
Dlg1
Iars2
Ddc
Srrm2
Pgm1
Ctsc
Cirbp
Atg3
Slco1a1
Cstb
Serpinh1
Phyhd1
Hspa13
Cope
Stip1
Scd1
Mrps30
Coro7
Farsa
Baiap2
Tnc
Adh1
Eif2s1
Rpl31
Tmx1
Cat
Iyd
Baat
Cfi
Pgrmc1
Ighg1
Nop56
Capns1
Alyref
Lifr
Slc2a2
Mybbp1a
Rps16
Pafah2
Lta4h
Hmgcr
Sf3b3
Gale
Slc10a1
Slc16a1
Dync1i2
Creg1
Lgmn
Vtn
Slc25a42
Cyp39a1
Ido2
Pts
Efhd2
Acin1
Rpl35a
Hmox1
Ilf3
Txndc12
Mcat
Arpc1b
Erp44
Txndc15
Magt1
Rpl22l1
Mpdu1
Hexa
Sorbs3
Trap1
Ppp1ca
Pex16
Sptan1
Abcg2
Dhrs7
Rpl37a
Emc2
Fxn
Rab10
Ebp
Pxmp2
Ndufa5
Manf
Tmed1
Hdhd3
Atp6v1b2
Capza2
Afmid
Elavl1
Fam21
Hnrnpdl
Acad11
Gstm7
Ube4a
Tpm1
Vps36
Arhgap17
Rpl10a
Nmnat3
Cml2
Pml
Gbp4
Rbp1
Cdo1
2011-09-01 00:00:00
Hsp90aa1
Eef1a1
Uso1
Pam16
2001-03-01 00:00:00
Setd3
Memo1
Rcc2
Anxa4
Acot2
Dhtkd1
Prdx2
Mpp6
Dnajc19
Ces1c
Mrpl13
Atl2
Lrrc47
Ube2l3
Amy2
Mapre1
Serpina1b
Srp9
Isoc2a
Bax
Pcyt2
Dnaja1
Fgl1
Dhrs3
Ndufs5
H2-D1
Hnrnpul2
Amacr
Galk1
Ldhb
Grsf1
Ndufb7
Lactb2
Rps13
Asgr2
Rpl35
H2afz;H2afv
Aqp1
Capg
Snx1
Cds2
Stim1
Cct7
Esyt1
Yars2
Sdpr
Dhdh
Chmp1a
Actb;
Mrpl53
Upp2
Rpl38
Edf1
Hmgb2
Akr1e2
Hspa4
Pex6
Uqcrh
Ppt1
Akr1b7
Arhgdib
Prkag1
Mup17
Pdzk1
Lamp1
Vcp
Ppp1cb
Rpl14
Stx7
Anp32b
Pdxk
Slc25a1
Hsph1
Cyp4b1
Wasl
Vps13c
Dnajc11
Ctsa
Col18a1
Eif2b5
Gc
Sntb1
Mp68
Glod4
Pmpcb
Rpl3
Psmc3
Rras
Hcls1
Ehd1
Marcksl1
Pgls
B2m
Cnpy3
Bsdc1
Acsl3
Tln2
Snap47
Echdc3
Coro1c
Ifi35
Rab32
Tubb4b
Ptgs1
Rbpms2
Erbb2ip
Gcsh
Nagk
Coa7
Sdf2l1
Anxa6
Mrps2
Rpl29
Cox7c
Orm1
Timm9
Hmgn2
Caprin1
Nono
ORF11
Dazap1
G3bp2
Akr1c13
Pycrl
Prkaa1
Rpl32
Ergic1
Fmo4
Supt5h
Chtop
St3gal5
Man1a1
Ppib
Cops5
Rbm25
Fermt3
Mri1
Clu
Cml1
Colgalt1
Erc1
Ap1g1
Tmed10
Nipsnap3b
Rps14
Mtnd4
Soat2
Rbbp7
Cdipt
Fermt2
Nme2
Bin2
Tap1
Ckap4
Cdh2
Nqo2
Cdv3
Txn
Serbp1
Rpl36
Hao2
Aasdhppt
Sec61a1
Safb
Nucks1
Mtch1
Cnn3
Smap2
Plxnb2
Emilin1
Asrgl1
Nudcd1
Pctp
Rps18
Bst2
Rpl9
Hnrnph1
Sbds
Apoa2
Eif3c
Inpp1
Tpmt
Tcp1
Ddx39b
Trip12
Rab2a
Amdhd1
Ndufaf4
Jup
Syap1
Rps3
Akr7a2
Shpk
Mmab
Psmd2
Vps25
Tomm40
Ptms
Coq5
Tomm34
Gdi2
Abcb7
Adpgk
Cisd3
H3f3c;H3f3a
Urod
Sec61b
Actr1a
Uap1
Lamc1
Rps25
Cldn3
Enpp1
Ccar2
Dhrsx
Pex1
Gclm
Abhd12
Mrpl46
Ddx21
Ctnnd1
Cops2
Rps21
Rsu1
Spryd4
Cyp2c29
Psmb6
Psmc6
Galk2
Phlda1
Fubp1
Scamp3
Akr1b8
Hp1bp3
Nmrk1
Stx18
Eif4b
Sfxn2
Rpl36a
Srsf4
Opa3
Pak2
Mthfs
Exosc6
Ptpn1
Chmp4b
Pgp
Myl6
Ndrg1
Lyplal1
Derl2
Fam134c
Mrpl28
Gsto1
Ccar1
Raly
Mlxipl
Ptges2
Mapre2
Ssr3
Nt5e
FAM120A
Cutc
Abhd3
Cacybp
Slc16a7
Khdrbs1
Srsf2
Mtx2
Top2b
Tmem135
Tuba4a
Palld
Timm13
Ilk
Tsg101
Slmap
Lhpp
Oxnad1
Hint1
Dpm1
Lad1
Usp4
Hnrnpa1
Hnrnpu
Aarsd1
Atp6v1a
Pecr
Fetub
Eif3i
Mgll
Gfer
Hamp2;Hamp
C8g
Rnh1
Prdx6
Aga
Hcfc1
Rps8
Serpind1
Xylb
Myo1b
Serhl
Hars
Psmc5
Dtx3l
Gcat
Mecp2
Sugt1
M6pr
Ap1b1
Cdc5l
Bnip3
Stard10
Timm50
Coasy
Atp13a1
Mrpl19
Rad23b
Aimp2
Tmed5
Atp5j
Gspt1
Aip
Mgat1
Itga5
Dnajb12
Tpp1
Cpn2
Bckdhb
Zc3h11a
Gfm2
Ggact
Ece1
Ubqln1
Nop58
Slco2b1
Tubb2a
Zc3hav1
Rps12
Rpl24
Bcl2l13
Myh11
Thumpd1
Ttc38
Hist1h1b
Rps26
Ppp1r21
Capzb
Ube2v1
Dhx29
Irf3
Mllt4
Rpl27
Cpeb4;Cpeb3;Cpeb2
Rexo2
Sec23ip
Cyp2b19
Snx3
Nsun2
Rbks
Sf3a1
Tmx2
Srsf10
Isg15
Mif
Ptprf
Bola1
Srsf5
Mat2a
Erh
Fn3krp
Ctage5
Fdft1
Cdc42ep1
Rbbp4
Capn1
Mcts1
Mtnd1
Nudt16
Epb41l5
Mocs1
Ssr4
Fndc3a
Cmpk1
Sel1l
Dnajc3
Srpr
H2-Q10
Sf3b1
Coq3
Pitpna
Sec23a
Srrt
Parp12
Fam136a
Emc7
Amfr
Tmem33
Pafah1b1
Eif5
Eif4e
Nubpl
Mrps15
Urah
Mrps27
Btd
Etf1
Sorbs2
Tinagl1
Chd4
Dpp9
Epb41l2
Timm10
Arfgef2
Arf5
Cops4
Tap2
Ufl1
Osbp
Mrc1
Acnat2
Adprhl2
Rps7
Mpc2
Set
Zmpste24
Vac14
Sepsecs
Nhlrc2
Sun2
Slc22a18
Golga2
Dpp3
Fam114a1
Sorbs1
Gusb
Slc25a45
Txlna
Gltpd2
Mrps34
Sh3bgrl3
Tor1aip1
Dcaf11
Serpina1d
Srp14
Tjp3
Preb
Nudc
Eif3h
Npepps
Acot4
Tcerg1
Wdr91
Dnm1l
Snf8
Apmap
Abce1
Wars
Lman1
Lsp1
Csnk2a1
Tpd52l2
Camk2b;Camk2g
Nfs1
S100a11
Dgat1
Derl1
Afg3l2
Akt2
Ptpn11
Xrn2
Tm6sf2
Nck1
Ndufv3
Xrcc6
Ica
Surf1
Abhd11
Prodh2
Glyr1
Ap1s1
Ppan
Acot8
Ppp6r3
Eefsec
Them4
Stk38
Arpc1a
Pygb
Tm7sf2
Pcbd1
Nceh1
Fads6
Man2b2
Hnrnpul1
Sh3glb1
Mrps6
Purb
Necap1
Cdc42ep4
Rab14
Pcbp2
L3hypdh
Rpl13a
St3gal1
Rsl1d1
Dhcr7
Rps23
Srprb
Prosc
Pepd
Arpc5l
Pgpep1
Apeh
Eif3k
Fam107b
Eif1a;Eif1ax
Rpl11
Pvrl1
Rps11
Galt
Hax1
Rps10
Ddrgk1
St13
Rps5
Mtx1
Gnai2
Twf1
Ybx1
Col4a1
Ctsh
Sdhd
Kpnb1
H2afx
Sephs1
Ppfibp2
Crk
Ostf1
Iah1
Ei24
Ambp
Gda
Nop16
Nsfl1c
Gstz1
Lgals9
Mfn1
Snw1
Icam1
Hmgn1
Crybb3
Sap18
Mrps9
Csrp1
Hectd3
Ythdf3
Chmp2b
Chmp2a
Amy1
Nfia
Golim4
Sfxn5
Amdhd2
Ttc39c
Pgm2
Babam1
Ank3
Smpd2
Clpb
Lars
Slc9a3r2
Nedd4
Lamtor1
Atp1a1
Ppm1b
Slirp
Mff
Hmgn5
Numb
Parp1
Pelo
Dag1
Mapk1
Mob1b
Ccdc58
Msra
Vps29
Map2k3
Chordc1
H2afy
Ugt2a2
Pi4k2a
Stk4
Mrpl45
Ap2b1
Ppap2b
Jchain
Gsr
Txnrd1
Erlin2
Ptbp1
Lias
Tfr2
Psma2
Stau1
Cad
Mrpl23
Apoc3
Etnk2
Mrpl47
Slc39a14
Sbf1
Pdcd6
Casp7
Poglut1
Mecr
Sars2
Pex7
Mrpl17
Tfrc
Nudt8
Dnm2
Ehd3
Sf1
Arl3
Psmd6
Esyt2
Sphk2
Txndc17
Mic13
Isoc2b
Rpl27a
Psmb3
Thrap3
Lgalsl
Mrpl43
Tmx3
Calm1
Arl1
Emd
Luc7l
Snrpa1
Cd2ap
Matr3
Tapt1
Usp7
Pitpnb
Fabp7
Lum
Tbc1d15
Clns1a
Ormdl2
Cfdp1
Cse1l
Cdkn2aip
Ppl
Hnrnpa3
Slk
Sfpq
Slc27a4
Pdap1
Sar1a
Acot7
Cpne3
Rpl23a
Helz2
Bcl2l1
Psmb4
Chchd6
Rab7a
Rdh14
Ctsb
Clic4
Ndufa3
Hspa4l
Fkbp15
Mrpl1
Prkar1a
Huwe1
Fam83h
Pawr
Capn2
Ndufaf2
Skp1
Hfe
Rps24
Cygb
Ppfibp1
Fam49b
Tmem19
Stx12
Fam98a
Coa3
Ywhae
Osgep
Tra2b
Rps15
Selo
Sec24a
Gadd45gip1
Myh14
Cpne1
Casp3
Bhmt2
Tbcel
Stxbp3
Ahsg
Fahd2
C1qbp
Mrps5
Fam195a
Ubr4
Snrpe
Snu13
Bche
Ap2m1
Acp1
Napa
Epb41
Bsg
Rpsa
Prkra
Naca
Eif3g
Manba
Xrcc5
Scarb1
Gpld1
Mpo
Dsc2
Sec62
Ppp6c
Cyp20a1
Eef1e1
Cr1l
Ceacam1
Pgk2
Usp9x
Dctn4
Lsm4
Fam162a
Ctbp1
Uchl5
Aak1
Atpif1
Mylk
Gm2a
Pea15
Prune2
Ggcx
Cdh1
Nars
Mlycd
Atp6v1g1
Psmd13
Dmd
Vimp
Stk24
Cda
Cct4
Api5
Ldlr
Ap2a2
Agk
Rps20
Pafah1b3
Ppp3ca
Tmed4
Lsm6
Lmf1
Ssr1
Sdr42e1
Slc25a16
Slc3a2
Spats2
Sntb2
Itga1
Mcee
Picalm
G3bp1
Tango2
Pnn
Hacd3
Mgst3
Eif3e
Stoml2
Copz2
Atp6v1e1
Myo1e
Ddi2
Sf3a3
Mtss1
Cul2
Csnk1a1
Gaa
Cyp7a1
Itgb2
Nup93
Hdhd2
Drg2
Fmo2
Gtf3c1
Ddx19a
Cdc42bpb
Rab5b
Orm2
Atp6v1h
Dhodh
Nedd8
Vps26a
Abhd16a
Ahcyl1
Reep6
F9
Ptprc
Clec3b
Btf3l4
Nutf2
Supt16h
Fam96a
Afm
Prpf19
Ogt
Flii
Cd1d1
Gfm1
Ifi204
Wbp11
Aup1
Trim25
Tns2
Ssrp1
Mrps22
Nrd1
Nub1
Hpn
Zpr1
Lin7a
Habp4
Top1
Pld4
Rpl17
Mocos
Aftph
Fkbp5
Rbbp9
Ppm1g
Psma5
Rer1
Slc47a1
Aldh8a1
Mtfr1l
Nap1l1
Srek1
Gosr2
Cybb
Tpr
Prkaa2
Dync1li2
Larp1
Dcakd
Prkar2a
Ywhag
Dynll2
Abcg8
Pex26
Cyfip1
Ap2s1
Tars2
Eif2b2
Acox3
Ube2d3
Slc27a5
Sec13
Dhx36
Rcn3
Gdi1
Itpr1
Rps27l
Tuba1c
Alg9
Ppp2r1a
Abhd5
Mrps21
Tceb1
Ago2
Polr2a
Gar1
Btf3
Exoc4
Lmf2
Cops6
Mtif2
Ssb
Arpc4
Tsn
Map2k2
Ccdc90b
C1qb
Smc1a
Psmd7
Sqstm1
Dnajc12
Pgrmc2
Sec61g
Mrpl37
Taco1
Grb7
Arfgef1
Cast
Gpx3
Gmpr2
Scrib
Luc7l2
Blmh
Rnps1
Rpl23
Glrx3
Sumo2
Ap2a1
Rras2
Kras
Ehd4
Snca
Arrb1
Apoa1bp
Mrps7
Ecm29
Sae1
Ptgr1
Sgk2
Eif3m
Akr1c18
Cers2
Uba52
Slc1a2
Syncrip
Map2k4
Usp10
Cfl1
Ik
Arih1
Eif4h
Tollip
Acmsd
Rela
Mrpl18
Cyp2d11
Dync1li1
Pnkp
Tomm70a
Ube2k
Lypla2
Dhx15
Pnp
Rmdn1
Snrpa
Psma3
Csde1
Snx4
Zadh2
Tmem126a
Mavs
Sdf2
Snrpd1
Mtus1
Slc25a4
Rcn2
Mal2
Prpsap2
Acsm1
Pisd
Scrn2
Ufsp2
Psmd8
Htra2
Mfn2
Hacd2
Evl
Eif5a
Rtn3
Dcaf8
Alg5
Rad23a
Nploc4
Nadsyn1
Smc3
Ufd1l
Slc25a23
Vbp1
Denr
Flad1
Psme3
Rap1b
Fam114a2
Nlrx1
Vps4b
Mycbp
Prpf40a
Hspa2
Pcmt1
Tmem56
Rpl34
Aspscr1
Guk1
Fkbp1a
Arpc2
Gnpda1
Npepl1
Ap1m1
Psip1
Mospd2
Rcc1
Flot1
Tmem38b
Srr
Cecr5
Csrp3
Ube2z
H2afy2
Snrpf
Rps15a
Psmd5
Gm10881
Hmbs
Mocs3
Sdf4
Nid1
Itpa
Arsb
Mrpl15
Pcyt1a
Myo1c
Dnaja2
Rabggta
Mtor
Cab39
Mydgf
Cyp7b1
Mat2b
Ubxn1
Nmt2
Chmp3
Ifih1
Diaph1
Eif5b
Mrps31
Ppp2r4
Atxn2l
Itsn1
Tram1
Rabgap1l
Eea1
Atp6v0a1
U2af2
Pfdn2
Tbc1d9b
Ttll12
Pald1
Mrpl48
Tom1
Gnai3
Fam98b
Bclaf1
Snrpd2
Dpy19l1
Cdc42
Brap
Eif6
Bre
Tubb6
Eif2s3x
Plbd2
Atxn2
Rps29
Timm17b
Wdr13
Fkbp3
Scyl2
Ppm1a
Ogfr
Psmd12
Rpl39
Wbp2
Abcb6
Magix
Surf4
Txn2
Hnrnpf
Crkl
Vps35
Cxadr
Golph3
Dap3
Mmaa
Sdsl
Sh2b1
Tsta3
Cops8
Spg20
Snrpb;Snrpn
Mrps28
Uros
Mpp1
Smap1
Mta2
Psmb1
Faf2
Gstm5
Cct6a
Ipo5
Prmt5
Arl6ip5
Nsf
Slc4a4
Hgs
Smarca5
Wasf2
Cgnl1
Cask
Gnb2
Iglc2
Gstp2
Dstn
Bcas2
Ddx39a
Hectd1
Sc5d
Ptpmt1
Nnmt
Cops7a
Slc6a12
Prpf4
Psmb7
Fam175b
Ube2v2
Sumo1
Csk
Prune
Mrpl14
Tnpo1
Sult1c2
Smu1
Gorasp2
Ddx3x
Scrn3
Apoo
Dnajb2
Atox1
Rbm28
Stom
Agfg1
Appl1
Ociad1
Tmpo
Hdgfrp2
Ghitm
Aars2
Eif4g3
Usp5
Asah1
Ccs
Prpf3
Ppp6r1
Mrpl11
Tsfm
Adsl
Nudt5
Sigirr
Mrpl40
Dctn1
Ywhab
Nat10
Tmcc1
Csnk2a2
Exosc4
Rhot2
Rps17
Mapk14
Pin1
Mfap1
Gmps
Ca14
Kiaa1033
Deptor
Ran
Fau
Serpina3n
Svs4
Gba
Abcg5
Timm23
Agpat6
Ola1
Fkbp2
Prkacb
Apoc1
Ppcs
Vapa
Dcun1d1
Thy1
Azgp1
Polr2h
Carm1
Alas1
Adss
Phka2
Gps1
Aox1
Rbm39
Gfpt1
Ncln
Apip
Rac1
Rac2
Rpl10
Tardbp
Oxsr1
Phgdh
Emc1
Pds5b
Pla2g12b
Efr3a
U2af1
Mettl13
Rheb
Osbpl9
Cul5
Hdgf
Fn3k
Eftud2
Ints4
Ccdc22
Rgl3
Zc3hc1
Flot2
Golga4
Actr1b
Faf1
Slc39a7
Usp15
Eva1a
Agpat3
Zc3h14
Ldah
Kif1b
Mrps23
Son
Cltb
Vrk3
Ruvbl2
Dtnb
Ptrh2
Pld3
Bag6
Toe1
Eif2b4
Copg2
Rangap1
Apoh
Mrpl22
Stx5
Birc6
Synj2bp
Pcbd2
Psmc4
Snx9
Nit1
Krt83
Apcs
Prkab1
Shc1
Arih2
Rtfdc1
Cd74
Sh3bgrl
Mtap
Kif5b
Sec11a
Bnip1
Hm13
Rbpms
Fam63a
Phkg2
Clasp2
Atg7
Acsf3
Dtd2
Tceb2
Pfas
Psmd14
Gna11
Eps15
Tagln
Araf
Oxr1
Alkbh3
Psma7
Mrps35
Pabpn1
Sugct
Trim33
Xpnpep3
Ywhaq
Ppil1
Mup20
Srrm1
Akap1
Tubb5
Ddah2
Gna13
Ankfy1
Ctnnbl1
Myo3b
Dek
Man2b1
Ubxn4
Lpcat3
Tfam
Clptm1
Celf1
Kpna3
Pcna
Arf6
Nhp2
Macf1
Smarce1
Galns
Rbm47
Shtn1
Mrpl3
Ptbp3
Cyp2c38
Cnot1
Eml2
Nif3l1
Pithd1
Atp1b3
Acsl4
Camk2d
Pacsin2
Prps1
Gmfb
Pebp1
Them6
Magoh
Hdac6
Sars
Tm9sf2
Psme4
Tial1
Dad1
Fbxo3
Epn1
Uba6
Zbtb8os
Aprt
Rdh13
Pde2a
Nampt
Drg1
Ckap5
Tm9sf4
Rbm17
Ppp4r3a
Tprkb
Gnas
Gbe1
Plaa
Tmod3
Lamtor3
Gimap8
Ecm1
Rab11b
Psmd1
Mrpl21
Rab5a
Mrrf
Nudt19
Creld2
Nudt21
Trappc3
Arhgef7
Kif21a
Alad
Tldc1
Chmp7
Mcu
U2surp
Ssbp1
Sipa1
Osbpl8
Gars
Inpp5b
Gm5571
Agfg2
Lyrm4
Akt1s1
Tmprss6
Lyrm5
Ccdc25
Add3
Sra1
Trmt112
Sh3gl2
Arf3;Arf1
Tmco1
Abcb4
Itfg3
Cdk5rap3
Ufm1
Rnf213
Ppp2r5e
Ezr
Plcg2
Atl3
Ostc
Prorsd1
Rmnd5a
Ipo7
Poldip3
Strap
Otub1
Cmtr1
Lrrfip2
Prkaca
Galm
Ube2i
Ppip5k2
Egfl8
Srsf9
Isoc1
Seh1l
Mipep
Eif4g2
Cox15
Lrba
Prrc2a
Pfdn6
Mrpl38
Lsm2
Nt5c
Gpx4
Nat2
Rab1b
Cct6b
Thop1
Tmem256
Eftud1
Myo1d
Pex14
Snx27
Golga3
Rpl22
Usp19
Arf4
Pef1
Lgals8
Cstf2
Ptcd3
Nxf1
Eif2a
Emc3
Nomo1
Ubtf
Cpsf6
Rhoa
Rab9a
Psmc2
Pxn
Sqle
Rpl15
Cul4a
Nae1
Otud4
Csnk2b
Rpl12
Acbd3
Lrrfip1
Pin4
Ppp2cb
Fan1
Bzw1
Ict1
Pls3
Gucy1b3
Uba5
Dpep1
Mesdc2
Dusp23
Anp32e
Eif2s2
Hnrnph2
Itgb5
Spag9
Cops3
Fbl
Nmt1
Glg1
Snrnp200
Mon2
Ero1b
Ppox
Xpo7
Tpm2;
2008-09-01 00:00:00
Mrpl50
Emc8
Eng
Pon2
Bpnt1
2015-09-01 00:00:00
Gapvd1
Fcho2
Gas2
Nt5c2
Psmb2
Tarsl2
Ada
Sfn
Mrpl41
Ddx6
Nudt2
Ptprd
Trnt1
Nln
Rab43
Srsf7
Cul3
Ppp2r5a
Saysd1
Ndufaf7
Adck4
Nup210
Ears2
Stab2
Kiaa0196
Cul4b
Eps15l1
Anxa3
Rala
Usp24
Uchl3
Ablim1
Cmas
Zc3h15
Rps2
Farp1
Ranbp3
H2-Ab1
Tgoln1
Rps27
Psmg1
Emc10
Wdr5
Gpcpd1
Ap3d1
Lpin1
Snrpg
Zfyve1
Mapk3
Hprt1
Kti12
Nudt14
Pex11g
Chp1
Mmgt1
Elovl1
Cherp
Eif4e2
Rnf185
Nt5c3a
Dnajc7
Cdkn1b
Col6a6
Nfu1
Snap29
Cox20
Ptges3
Cbx1
Map2k1
Pip4k2c
Rab4b
Naa15
Mrps17
Ktn1
Krt76
Arpp19
Sec63
Rps27a
Rtn4
Iba57
Tbrg4
Flnc
Psmc1
Psmd11
Ube3a
Gyg1
Dysf
Phpt1
Arl8b
Krt33a
Rdh10
Tbcb
Nek7
Stat5b
Pfkp
Krt86;Krt81
Smarcc1;Smarcc2
Sirt2
Cpq
Jakmip3
Sco1
Sirt3
Eif3j1
Ncbp1
Yme1l1
Gnl1
Add1
Mtfp1
Rilp
Rxra
Map2k6
Larp4
Col6a5
Armc1
Plp1
Dtd1
Plekha6
Herpud1
Myh10
Rab8a
Vamp8
Rap1a
Dnajb1
Mrpl9
Puf60
Atp1b1
S100a4
Dusp3
Trmt11
Atp2b1
Ppme1
Hdac1
Clcc1
Mrps24
Sec16b
Zfr
Hook3
Ndufaf6
Ifi205b;Ifi205a
Fbxo22
Fxr1
Mrpl39
Palmd
Hnrnpll
Szrd1
Clip1
Ap3m1
Slc20a2
Snap23
Ctsl
Nid2
Mzb1
Odr4
F10
Tcof1
Clint1
Mrpl24
Usp47
Eif1
Ptgr2
Krt33b;
Scamp1
Naa25
Alg2
Pafah1b2
Nckap1
Glod5
Hpcal1
Osbpl11
Ldlrap1
Edc4
Tcea1
Fdxr
Cul1
Emc4
Abcc3
Ccdc91
Map7
Igbp1
Ranbp2
Rbx1
Usp14
Grb14
Acyp1
Ncstn
Bin1
Cdc73
Gcc2
Nufip2
Rtn4ip1
Man2a2
Dio1
Parva
Dhx30
Pnpt1
Gtf3c5
Pcnp
Commd3
Ca8
Osbpl1a
Mrpl4
Sgta
Tor1a
Prpsap1
Hnmt
Naa50
Metap1
Coa6
S100a13
Asna1
Bccip
Nr3c1
Plvap
Fam91a1
Yif1b
Map1s
Ppp1r12c
Srm
Tor1aip2
Ppp5c
Ogn
Cd82
Nup214
Trim56
Rhot1
Snrpd3
Atad1
Ngef
Ccdc51
Psmf1
Vps45
Gtpbp1
Zzef1
Dynlrb1
Rasip1
Idnk
Mtpn
Elac2
Ubqln2
Gigyf2
Rbm8a
Tubb1
Myadm
Aamdc
Pmm2
Gak
Kiaa1468
Rprd1b
Fbn1
Txndc9
Gk5
Psmd3
Dhfr
Naa11;Naa10
Fnta
Afg3l1
Eif3f
Slc7a2
Klc4
Nmral1
Polr2b
Ubap2l
Hexim1
Tm9sf3
Fscn1
Bub3
Ppp2r2a
Dhrs11
Abca6
Tns3
Cdk9
Ciapin1
Mt1
Fbln5
Gnpnat1
Napg
Ptdss1
Rbms3;Rbms1
Xpo1
Gk2
Ist1
F12
Adrm1
Ints3
Phactr4
Col5a1
Svs5
Rragd
Prpf8
Metap2
Prpf6
Lcat
Agt
Nap1l4
Ecsit
Dkc1
Cdk6
Tjp2
Mbp
Oxa1l
Rpl30
Prmt1
Psmd4
Cd38
Ccdc93
Mib1
Taok3

In [38]:
pwd

'C:\\Users\\91918'

In [39]:
df2=pd.read_excel("liver proteome.xlsx")

In [40]:
df2

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [61]:
filtered_df2= df2[df2["Comparison (group1/group2)"] == "Y_NRDR / Y_AL"]
print(filtered_df2)

      Comparison (group1/group2)   Group ProteinGroups  AVG Log2 Ratio  \
8                  Y_NRDR / Y_AL  Q8C196        Q8C196        0.441013
99                 Y_NRDR / Y_AL  Q99LB7        Q99LB7        0.236349
113                Y_NRDR / Y_AL  O88833        O88833        1.593028
123                Y_NRDR / Y_AL  Q99K67        Q99K67        0.921387
157                Y_NRDR / Y_AL  P52825        P52825        0.587015
...                          ...     ...           ...             ...
85264              Y_NRDR / Y_AL  P10711        P10711       -0.085954
85272              Y_NRDR / Y_AL  Q62087        Q62087        0.009904
85276              Y_NRDR / Y_AL  Q8BG05        Q8BG05       -0.062646
85284              Y_NRDR / Y_AL  Q9ESD7        Q9ESD7        0.009113
85291              Y_NRDR / Y_AL  P27786        P27786        0.043313

       Absolute AVG Log2 Ratio         Pvalue         Qvalue  # of Ratios  \
8                     0.441013  9.427715e-189  4.330464e-185         3491
99                    0.236349   6.423189e-72   2.655346e-69         1243
113                   1.593028   7.367441e-69   2.671667e-66          235
123                   0.921387   4.236871e-67   1.412518e-64          950
157                   0.587015   1.850490e-61   4.841726e-59          467
...                        ...            ...            ...          ...
85264                 0.085954   9.991991e-01   4.844474e-01           84
85272                 0.009904   9.994199e-01   4.845157e-01          179
85276                 0.062646   9.995017e-01   4.845316e-01          468
85284                 0.009113   9.996780e-01   4.845820e-01           29
85291                 0.043313   9.998716e-01   4.846165e-01          312

      UniProtIds    Genes                                ProteinDescriptions  \
8         Q8C196     Cps1  Carbamoyl-phosphate synthase [ammonia], mitoch...
99        Q99LB7    Sardh             Sarcosine dehydrogenase, mitochondrial
113       O88833  Cyp4a10                               Cytochrome P450 4A10
123       Q99K67     Aass  Alpha-aminoadipic semialdehyde synthase, mitoc...
157       P52825     Cpt2  Carnitine O-palmitoyltransferase 2, mitochondrial
...          ...      ...                                                ...
85264     P10711    Tcea1        Transcription elongation factor A protein 1
85272     Q62087     Pon3                      Serum paraoxonase/lactonase 3
85276     Q8BG05  Hnrnpa3         Heterogeneous nuclear ribonucleoprotein A3
85284     Q9ESD7     Dysf                                          Dysferlin
85291     P27786  Cyp17a1           Steroid 17-alpha-hydroxylase/17,20 lyase

      ProteinNames  # Unique Total Peptides    % Change     Ratio  \
8       CPSM_MOUSE                      151   35.755700  1.357557
99     SARDH_MOUSE                       62   17.800752  1.178008
113    CP4AA_MOUSE                       22  201.681844  3.016818
123     AASS_MOUSE                       54   89.393485  1.893935
157     CPT2_MOUSE                       31   50.213546  1.502135
...            ...                      ...         ...       ...
85264  TCEA1_MOUSE                        8   -5.783867  0.942161
85272   PON3_MOUSE                       12    0.688877  1.006889
85276   ROA3_MOUSE                       25   -4.249371  0.957506
85284   DYSF_MOUSE                        2    0.633664  1.006337
85291  CP17A_MOUSE                       23    3.047774  1.030478

      Condition Numerator Condition Denominator  \
8                  Y_NRDR                  Y_AL
99                 Y_NRDR                  Y_AL
113                Y_NRDR                  Y_AL
123                Y_NRDR                  Y_AL
157                Y_NRDR                  Y_AL
...                   ...                   ...
85264              Y_NRDR                  Y_AL
85272              Y_NRDR                  Y_AL
85276              Y_NRDR                  Y_AL
85284              Y_NRDR                  Y_AL
85291              Y_NRDR                  Y_AL

                                   GO Cellular Component  \
8      nucleolus,mitochondrion,mitochondrial inner me...
99                    mitochondrion,mitochondrial matrix
113    cytoplasm,endoplasmic reticulum membrane,apica...
123    mitochondrion,intracellular membrane-bounded o...
157    nucleoplasm,nucleolus,mitochondrion,mitochondr...
...                                                  ...
85264  nucleus,nucleoplasm,transcription factor TFIID...
85272  extracellular space,intracellular membrane-bou...
85276                               spliceosomal complex
85284  endosome,early endosome,late endosome,microtub...
85291     mitochondrion,membrane,axon,neuronal cell body

                                   GO Molecular Function  \
8      carbamoyl-phosphate synthase (ammonia) activit...
99                      sarcosine dehydrogenase activity
113    monooxygenase activity,iron ion binding,arachi...
123    saccharopine dehydrogenase (NADP+, L-lysine-fo...
157            carnitine O-palmitoyltransferase activity
...                                                  ...
85264       DNA binding,protein binding,zinc ion binding
85272  aryldialkylphosphatase activity,arylesterase a...
85276                                        RNA binding
85284  calcium ion binding,protein binding,phospholip...
85291  steroid 17-alpha-monooxygenase activity,iron i...

                                   GO Biological Process
8      urea cycle,'de novo' pyrimidine nucleobase bio...
99     oxidation-reduction process,sarcosine cataboli...
113    fatty acid metabolic process,leukotriene B4 ca...
123    generation of precursor metabolites and energy...
157               fatty acid metabolic process,transport
...                                                  ...
85264  transcription, DNA-templated,erythrocyte diffe...
85272  response to toxic substance,phenylacetate cata...
85276                       mRNA processing,RNA splicing
85284  plasma membrane repair,vesicle fusion,muscle c...
85291  glucocorticoid biosynthetic process,steroid me...

[3040 rows x 20 columns]

In [62]:
num_genes = filtered_df2["Genes"].count()
print(f"Total number of genes in 'Y_NRDR / Y_AL': {num_genes}")

Total number of genes in 'Y_NRDR / Y_AL': 2991

In [63]:
num_unique_genes = filtered_df2["Genes"].nunique()
print(f"Total number of unique genes: {num_unique_genes}")

Total number of unique genes: 2991

In [64]:
num_na_genes = filtered_df2["Genes"].isna().sum()
print(f"Number of NaN values in 'Genes': {num_na_genes}")

Number of NaN values in 'Genes': 49

In [66]:
num_na_genes = pd.isna(unique_genes).sum()
print(f"Number of NaN values in unique genes: {num_na_genes}")

Number of NaN values in unique genes: 0